### ISSUE TITLE
Steam Play Text Warped in Linux

### ISSUE THREAD

**Issue by applesea2** [Outsetini/Air-for-Steam#202] opened 2018-09-03 05:28 UTC
As soon as Valve released Steam Play for the beta client, the text "run's on this computer via Steam Play" appears warped and put in the top left, rather than next to the title.
![screenshot from 2018-09-03 01-28-15](https://user-images.githubusercontent.com/20137421/44968929-a8bf8600-af18-11e8-9047-1200de0ec5fb.png)

**Comment by jcstryker** [comment] 2018-09-07 17:56
I also have this issue with air-for-steam on linux.

**Comment by Outsetini** [comment] 2018-09-12 21:18
Duplicate of #200

**Closed by Outsetini** 2018-09-12 21:18 UTC
Labels: Linux
