### ISSUE TITLE
Links deprecated

### ISSUE THREAD

**Issue by silas229** [Outsetini/Air-for-Steam#170] opened 2018-03-02 22:32 UTC
The links in https://github.com/Outsetini/Air-for-Steam/wiki#how-to-fix-overlay-text-being-cut-off-in-other-languages are deprecated.

**Comment by andrewjmetzger** [comment] 2018-03-04 23:32
Addressed in wiki commit [cfbe052](https://github.com/Outsetini/Air-for-Steam/wiki/Home/_compare/595d516897df7e0f4cb4cee019997aa3e7bf3bdb...cfbe05272e0ddf0cd82b648949df080655d7c730).

Because GitHub does not support closing issues with a wiki commit, please review the linked diff, and if the issue is resolved, mark it as closed. If not, comment here and we can work on it some more.

**Comment by Outsetini** [comment] 2018-03-06 04:33
Looks good to me, thanks for the help @andrewjmetzger! Please re-open if it's not working properly now.

**Closed by Outsetini** 2018-03-06 04:33 UTC
