### ISSUE TITLE
Download speed graph not contained in window

### ISSUE THREAD

**Issue by pitothepowerof3** [outsetini/Air-for-Steam#107] opened 2016-03-13 18:41 UTC
### Issue ###
The download speed history graph will not stay inside the bounds of the client window.  It's barely visible against the launcher. This seems like it could be on valve's end.

### System ###
Running Air for Steam 2016-0311 on latest Steam Client Beta  (last updated March 11, 2016). OS is Ubuntu 15.10, if it's relevant. 

### Steps to recreate ###
On latest steam beta with latest Air skin, initiate a download and go to the downloads page. 

![image](https://cloud.githubusercontent.com/assets/9117849/13730552/66f1b330-e920-11e5-93c7-29a312e607f6.png)

**Comment by outsetini** [comment] 2016-03-21 04:00
I'm not sure if I'm seeing this on my end, do you mean that the graph is actually showing literally outside of the client? Can you highlight it in your screenshot?

Also, can you verify if this is happening on the default theme as well?

**Comment by outsetini** [comment] 2016-04-03 23:04
Unable to reproduce, closing for now. Please feel free to re-open if this continues to be an issue.

**Closed by outsetini** 2016-04-03 23:04 UTC
Labels: bug
